version: "3.7"

networks:
  default:
    name: Servarr
    external: true

services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped

  radarr-4k:
    container_name: radarr-4k
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7879:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr-4k:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - "8686:8686"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/overseerr:/config
    restart: unless-stopped

  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    environment:
      - TZ=${TZ}
      - PMM_TIME=03:00,09:00,15:00,21:00
    volumes:
      - ${CONFIG_PATH}/plex-meta-manager:/config
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped

  qbittorrent:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent
    volumes:
      - ${MEDIA_PATH}:/data
      - ${CONFIG_PATH}/qbittorrent-vpn:/config
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - VPN_USER=${OPENVPN_USERNAME}
      - VPN_PASS=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=yes
      - OPENVPN_CONFIG=bahamas
      - LAN_NETWORK=${LAN}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DNS=8.8.8.8
    ports:
      - 8080:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    ports:
      - "8090:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sabnzbd:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    volumes:
      - ${CONFIG_PATH}/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    ports:
      - 8181:8181
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265
      - 8266:8266
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=LocalNode
    volumes:
      - ${CONFIG_PATH}/tdarr/server:/app/server
      - ${CONFIG_PATH}/tdarr/configs:/app/configs
      - ${CONFIG_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_PATH}:/plex_media
      - ${MEDIA_PATH}/transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  watchtower:
    container_name: watchtower
    image: beatkind/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.43
      - WATCHTOWER_SCHEDULE=0 0 7 ? * *
      - WATCHTOWER_CLEANUP=true
      - TZ=${TZ}

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ALLOWED_NETWORKS=${ALLOWED_NETWORKS}
      - TZ=${TZ}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${MEDIA_PATH}/transcode_cache:/transcode
      - ${MEDIA_PATH}/TV_Shows:/volume1/Plex_Media/TV_Shows
      - ${MEDIA_PATH}/Movies:/volume1/Plex_Media/Movies
      - ${MEDIA_PATH}/Music:/volume1/Plex_Media/Music
      - ${MEDIA_PATH}/Concerts:/volume1/Plex_Media/Concerts
      - ${MEDIA_PATH}/Preroll:/volume1/Plex_Media/Preroll
      - ${MEDIA_PATH}/4k_Movies:/volume1/Plex_Media/4k_Movies
      - ${CONFIG_PATH}/plex-dlna:/usr/lib/plexmediaserver/Resources/Profiles
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - "6767:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${MEDIA_PATH}:/data

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: "${PUID}:${PGID}"
    volumes:
      - ${CONFIG_PATH}/recyclarr:/config
    environment:
      - TZ=${TZ}
      - RECYCLARR_CREATE_CONFIG=true
      - CRON_SCHEDULE=0 0/15 * ? * * *

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  jenkins:
    image: chadwpalm/jenkins-docker:latest
    container_name: jenkins
    environment:
      - TZ=${TZ}
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/jenkins:/var/jenkins_home
    restart: unless-stopped

  lumunarr:
    image: chadwpalm/lumunarr:develop
    container_name: lumunarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/lumunarr:/config
    restart: unless-stopped
    network_mode: "host"

  autoheal:
    container_name: autoheal
    restart: always
    image: willfarrell/autoheal:1.2.0
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=10
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prerollplus:
    image: chadwpalm/prerollplus:develop
    container_name: prerollplus
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prerollplus:/config
      - ${MEDIA_PATH}/Preroll:/prerolls
    restart: unless-stopped
    network_mode: "host"

  comingsoon:
    image: chadwpalm/coming-soon:latest
    container_name: comingsoon
    environment:
      - CRON_SCHEDULE=0 */3 * * *
      - TZ=${TZ}
      - INPUT_FILE=ComingSoon.mp4
      - ICAL_URL_RADARR=${ICAL_URL_RADARR}
      - ICAL_URL_SONARR=${ICAL_URL_SONARR}
      - FONT_SIZE=50
      - FONT_COLOR=white
      - X_COORD=300
      - Y_COORD=150
      - START_TIME=5
      - END_TIME=13
      - UID=${PUID}
      - GID=${PGID}
      - LINE_SPACING=30
      - CENTER_TEXT=true
    volumes:
      - ${CONFIG_PATH}/coming-soon:/config
      - ${MEDIA_PATH}/Preroll/ComingSoon:/output
    restart: unless-stopped
    network_mode: "host"

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: "${PUID}:${PGID}"
    ports:
      - "2468:2468"
    volumes:
      - ${CONFIG_PATH}/cross-seed:/config
      - ${CONFIG_PATH}/qbittorrent-vpn/qBittorrent/data/BT_backup:/torrents:ro
      - ${MEDIA_PATH}/torrents:/cross-seeds
      - ${MEDIA_PATH}:/data
    environment:
      - TZ=${TZ}
    command: daemon
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    user: "${PUID}:${PGID}"
    volumes:
      - ${CONFIG_PATH}/autobrr:/config
    ports:
      - 7474:7474

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/homarr:/appdata
      - ${CONFIG_PATH}/homarr/custom-images:/app/apps/nextjs/public/custom-images
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - TZ=${TZ}
    ports:
      - "7575:7575"

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_OVERRIDE_OS=DSM
      - DASHDOT_FS_VIRTUAL_MOUNTS=/dev/mapper/cachedev_0,/dev/mapper/cachedev_1
      - DASHDOT_FS_DEVICE_FILTER=nvme0n1,nvme1n1,sata1,sata2,sata3,sata4,synoboot

  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    volumes:
      - ${CONFIG_PATH}/qbit-manage:/config:rw
      - ${MEDIA_PATH}/torrents:/data/torrents:rw
      - ${CONFIG_PATH}/qbittorrent-vpn/qBittorrent:/qbittorrent:ro
    environment:
      - QBT_RUN=false
      - QBT_SCHEDULE=15
      - QBT_CONFIG=/config/config.yml
      - QBT_LOGFILE=activity.log
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=true
      - QBT_TAG_UPDATE=true
      - QBT_REM_UNREGISTERED=true
      - QBT_REM_ORPHANED=true
      - QBT_TAG_TRACKER_ERROR=true
      - QBT_TAG_NOHARDLINKS=false
      - QBT_SHARE_LIMITS=true
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=false
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
      - QBT_SKIP_QB_VERSION_CHECK=true
      - TZ=${TZ}
    restart: on-failure:2

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${MEDIA_PATH}:/data
      - ${CONFIG_PATH}/unpackerr:/config
    restart: always
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - UN_LOG_FILE=/config/unpackerr.log
      - UN_SONARR_0_URL=http://${SERVER_IP}:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://${SERVER_IP}:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_1_URL=http://${SERVER_IP}:7879
      - UN_RADARR_1_API_KEY=${RADARR4K_API_KEY}
      - UN_LIDARR_0_URL=http://${SERVER_IP}:8686
      - UN_LIDARR_0_API_KEY=${LIDARR_API_KEY}
